# Generated by Django 4.0.4 on 2022-04-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='country',
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(help_text='Enter full address with country', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='unitmeasure',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
