# Generated by Django 4.0.4 on 2022-04-21 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_supplier_country_supplier_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=150)),
                ('attachedFile', models.FileField(upload_to='')),
                ('contentType', models.CharField(max_length=150)),
                ('dateOfUpload', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partCategoryFk', to='api.partcategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='pocName',
        ),
        migrations.AddField(
            model_name='supplier',
            name='poc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplierPoc', to='api.people'),
        ),
        migrations.CreateModel(
            name='StockCurrent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currentStock', models.PositiveIntegerField()),
                ('lastUpdateDate', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockCurrentPart', to='api.part')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplierFk', to='api.supplier'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poNumber', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('dateOrdered', models.DateField()),
                ('Eta', models.DateField()),
                ('dateDelivered', models.DateField(null=True)),
                ('status', models.BooleanField(default=False, help_text='order status, true-> delivered, false-> incomplete')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderPart', to='api.part')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unitFk', to='api.unitmeasure')),
            ],
        ),
        migrations.CreateModel(
            name='MinimumStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minimumStock', models.PositiveIntegerField()),
                ('lastUpdateDate', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minStockPart', to='api.part')),
            ],
        ),
    ]
