# Generated by Django 4.0.4 on 2022-04-22 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_attachment_part_remove_supplier_pocname_supplier_poc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachedFile',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='contentType',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='fileName',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplierFk', to='api.supplier'),
        ),
    ]
