# Generated by Django 4.0.4 on 2022-04-22 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_currentstock_delete_stockcurrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('attachment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivingAttachment', to='api.attachment')),
                ('orderItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivingOrder', to='api.order')),
            ],
        ),
    ]
