# Generated by Django 4.0.4 on 2022-04-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_receiving'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Eta',
            new_name='eta',
        ),
        migrations.AlterField(
            model_name='order',
            name='dateOrdered',
            field=models.DateTimeField(),
        ),
    ]
