# Generated by Django 4.0.4 on 2022-04-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_eta_order_eta_alter_order_dateordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dateOrdered',
            field=models.DateField(),
        ),
    ]
