# Generated by Django 4.0.4 on 2022-04-27 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_order_dateordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=False, help_text='order status, true-> delivered, false-> incomplete', on_delete=django.db.models.deletion.CASCADE, related_name='orderStatus', to='api.status'),
        ),
    ]
