# Generated by Django 4.0.4 on 2022-05-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_part_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='order',
            name='received',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
