# Generated by Django 4.0.4 on 2022-06-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_order_options_order_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='received',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
