# Generated by Django 4.0.4 on 2022-06-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_order_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='received',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
